#!/usr/bin/env bash
# a shell script for starting the March2Comp automatic March generation tool
set -e

function gcc9_cmake() {
	scl enable devtoolset-9 "cmake ."
}

function conda_toggle() {
	source /eda/anaconda3/bin/activate March2Comp
}

case $1 in
"compile")
	if [ $# -ne 1 ];then
		echo "Compilation command: March2Comp compile"
	else
		gcc9_cmake
		make
	fi
;;
"gen")
	if [ $# -ne 2 ];then
		echo "Compilation command: March2Comp compile"
		echo "March generation command: March2Comp gen <fault list filename>"
		echo "Fault simulation command: March2Comp sim <march test filename> <fault list filename>"
	else
		conda_toggle && python3 March2Comp.py $2
		cat ./results/generation_report.txt
	fi
;;
"sim")
	if [ $# -ne 3 ];then
		echo "Compilation command: March2Comp compile"
		echo "March generation command: March2Comp gen <fault list filename>"
		echo "Fault simulation command: March2Comp sim <march test filename> <fault list filename>"
	else
		cd ./sim
		conda_toggle && python3 sim2comp.py $2 $3
		cat ../results/simulation_report.txt
	fi
;;
*)
	echo "Compilation command: March2Comp compile"
	echo "March generation command: March2Comp gen <fault list filename>"
	echo "Fault simulation command: March2Comp sim <march test filename> <fault list filename>"
esac
